#local_backend: true
backend:
  name: git-gateway
  repo: githubuser/repo
  branch: main 
media_folder: 'assets/img'
collections:
  - name: "indexs"
    label: "Home Page"
    extension: "md"
    editor:
      preview: false
    files:
     - file: "index.md"
       label: "Update Home Page Design"
       name: "index"
       widget: list
       fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Cover Image', name: 'image', widget: 'image' }
          - name: 'button1'
            label: 'Button 1' 
            widget: 'object'
            fields:
             - { name: 'text', label: 'Text', widget: 'string' }
             - { name: 'link', label: 'Link', widget: 'string' }
          - name: 'button2'
            label: 'Button 2' 
            widget: 'object'
            fields:
             - { name: 'text', label: 'Text', widget: 'string' }
             - { name: 'link', label: 'Link', widget: 'string' }
          - name: 'features'
            label: 'Features Section' 
            widget: 'object'
            fields:
             - { name: 'intro', label: 'Intro', widget: 'string' }
             - { name: 'title', label: 'Title', widget: 'string' }
             - name: 'list1'
               label: 'List 1' 
               widget: 'object'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'icon', label: 'Icon', widget: 'image' }
                - { name: 'text', label: 'Text', widget: 'string' }
             - name: 'list2'
               label: 'List 2' 
               widget: 'object'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'icon', label: 'Icon', widget: 'image' }
                - { name: 'text', label: 'Text', widget: 'string' }
             - name: 'list3'
               label: 'List 3' 
               widget: 'object'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'icon', label: 'Icon', widget: 'image' }
                - { name: 'text', label: 'Text', widget: 'string' }
             - name: 'list4'
               label: 'List 4' 
               widget: 'object'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'icon', label: 'Icon', widget: 'image' }
                - { name: 'text', label: 'Text', widget: 'string' }
          - name: 'github'
            label: 'Github Section' 
            widget: 'object'
            fields:
             - { name: 'intro', label: 'Intro', widget: 'string' }
             - { name: 'title', label: 'Title', widget: 'string' }
             - { name: 'text', label: 'Text', widget: 'text' }
             - name: 'list'
               label: 'List' 
               widget: 'list'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'number', label: 'Number', widget: 'number' }
             - name: 'star'
               label: 'Github Star' 
               widget: 'object'
               fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - { name: 'number', label: 'Number', widget: 'number' }
          - name: 'section'
            label: 'Section Area' 
            widget: 'object'
            fields:
             - { name: 'intro', label: 'Intro', widget: 'string' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'start'
            label: 'Start Area' 
            widget: 'object'
            fields:
             - { name: 'intro', label: 'Intro', widget: 'string' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'start_python'
            label: 'Python Start Area' 
            widget: 'object'
            fields:
             - { name: 'icon', label: 'Icon', widget: 'image' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'start_javascript'
            label: 'Javascript Start Area' 
            widget: 'object'
            fields:
             - { name: 'icon', label: 'Icon', widget: 'image' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'start_java'
            label: 'Java Start Area' 
            widget: 'object'
            fields:
             - { name: 'icon', label: 'Icon', widget: 'image' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'start_c'
            label: 'C Start Area' 
            widget: 'object'
            fields:
             - { name: 'icon', label: 'Icon', widget: 'image' }
             - { name: 'title', label: 'Title', widget: 'string' }
          - name: 'faq'
            label: 'FAQ Section' 
            widget: 'object'
            fields:
             - { name: 'intro', label: 'Intro', widget: 'string' }
             - { name: 'title', label: 'Title', widget: 'string' }
             - name: 'list_active'
               label: 'QA List Active' 
               widget: 'object'
               fields:
                - { name: 'q', label: 'Question', widget: 'string' }
                - { name: 'a', label: 'Answer', widget: 'text' }
             - name: 'list'
               label: 'QA Faq List' 
               widget: 'list'
               fields:
                - { name: 'q', label: 'Question', widget: 'string' }
                - { name: 'a', label: 'Answer', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "settup"
    label: "Settings"
    extension: "yml"
    editor:
      preview: false
    files:
     - file: "_config.yml"
       label: "Site Settup"
       name: "config"
       widget: list
       fields:
         - { name: 'title', label: 'Title', widget: 'string' }
         - { name: 'description', label: 'Description', widget: 'string' }
         - { name: 'favicon', label: 'Favicon', widget: 'image'}
         - { name: 'logo', label: 'Logo', widget: 'image'}
         - { name: 'image', label: 'Image', widget: 'image'}
         - { name: 'lang', label: 'Site Lang', widget: 'string'}
         - { name: 'locale', label: 'Site Locale', widget: 'string'}
         - { name: 'url', label: 'URL', widget: 'string'}
         - name: 'navbar'
           label: 'Navbar Setup' 
           widget: 'object'
           fields:
            - { name: 'logo', label: 'Nav Logo', widget: 'image' }
            - { name: 'button', label: 'Nav Button', widget: 'string'}
            - name: 'list'
              label: 'Navbar List' 
              widget: 'list'
              fields:
               - { name: 'nav', label: 'Nav Name', widget: 'string' }
               - { name: 'link', label: 'Nav URL Link', widget: 'string'}
         - name: 'connect'
           label: 'Connect Setup' 
           widget: 'object'
           fields:
            - { name: 'title', label: 'Connect Title', widget: 'string' }
            - name: 'list'
              label: 'Connection List' 
              widget: 'list'
              fields:
               - { name: 'title', label: 'Title', widget: 'string' }
               - { name: 'icon', label: 'Icon', widget: 'image' }
               - { name: 'link', label: 'Nav URL Link', widget: 'string'}
         - name: 'contact_form'
           label: 'Contact Form Setup' 
           widget: 'object'
           fields:
            - { name: 'title', label: 'Contact Title', widget: 'string' }
            - { name: 'description', label: 'Contact Description', widget: 'string' }
            - { name: 'button', label: 'Contact Button', widget: 'string' }
            - { name: 'email', label: 'Contact Email Form', widget: 'string' }
         - name: 'contact_info'
           label: 'Contact Information' 
           widget: 'object'
           fields:
            - { name: 'title', label: 'Contact Title', widget: 'string' }
            - { name: 'phone_title', label: 'Contact Phone Title', widget: 'string' }
            - name: 'contact_phone'
              label: 'Contact Phone List' 
              widget: 'list'
              fields:
               - { name: 'text', label: 'Contact Phone Title', widget: 'string' }
               - { name: 'number', label: 'Phone Number', widget: 'string' }
            - { name: 'email_title', label: 'Contact Email Title', widget: 'string' }
            - name: 'contact_email'
              label: 'Contact Email List' 
              widget: 'list'
              fields:
               - { name: 'text', label: 'Contact Email Title', widget: 'string' }
               - { name: 'mail', label: 'Email Address', widget: 'string' }
         - name: 'footer'
           label: 'Footer Setup' 
           widget: 'object'
           fields:
            - { name: 'title', label: 'Footer Title', widget: 'string' }
            - { name: 'text', label: 'Footer Text', widget: 'string'}
            - name: 'button'
              label: 'Footer Button' 
              widget: 'list'
              fields:
               - { name: 'text', label: 'Button Text', widget: 'string'}
               - { name: 'icon', label: 'Icon', widget: 'image' }
               - { name: 'link', label: 'Button URL Link', widget: 'string'}
         - { name: 'copyrights', label: 'Copyrights', widget: 'string'}
         - name: 'social'
           label: 'Social Media' 
           widget: 'object'
           fields:
            - { name: 'facebook', label: 'Facebook URL Link', widget: 'string' }
            - { name: 'twitter', label: 'Twitter URL Link', widget: 'string'}
            - { name: 'instagram', label: 'Instagram URL Link', widget: 'string' }
            - { name: 'youtube', label: 'Youtube URL Link', widget: 'string' }
            - { name: 'whatsapp', label: 'Whatsapp URL Link', widget: 'string' }
  - name: "dashcode"
    label: "Dashboard Code"
    extension: "html"
    editor:
      preview: false
    files:
     - file: "_includes/code/dashboard.html"
       label: "Setup Dashboard Code"
       name: "dashboard"
       widget: list
       fields:
          - { label: 'Body', name: 'body', widget: 'text' }
  - name: "pycode"
    label: "Python Code"
    extension: "html"
    editor:
      preview: false
    files:
     - file: "_includes/code/python.html"
       label: "Setup Python Code"
       name: "python"
       widget: list
       fields:
          - { label: 'Body', name: 'body', widget: 'text' }
  - name: "jscode"
    label: "JavaScript Code"
    extension: "html"
    editor:
      preview: false
    files:
     - file: "_includes/code/javascript.html"
       label: "Setup JavaScript Code"
       name: "javascript"
       widget: list
       fields:
          - { label: 'Body', name: 'body', widget: 'text' }
  - name: "jacode"
    label: "Java Code"
    extension: "html"
    editor:
      preview: false
    files:
     - file: "_includes/code/java.html"
       label: "Setup Java Code"
       name: "java"
       widget: list
       fields:
          - { label: 'Body', name: 'body', widget: 'text' }
  - name: "cscode"
    label: "C# Code"
    extension: "html"
    editor:
      preview: false
    files:
     - file: "_includes/code/c.html"
       label: "Setup C# Code"
       name: "c"
       widget: list
       fields:
          - { label: 'Body', name: 'body', widget: 'text' }
  - name: "devs"
    label: "Developer"
    extension: "yml"
    editor:
      preview: false
    files:
     - file: "_config.yml"
       label: "Your Lovely Developer"
       name: "devs"
       widget: list
       fields:
         - name: 'developer'
           label: 'Jekyll Developer' 
           widget: 'object'
           fields:
            - { name: 'name', label: 'The Developer', widget: 'select' , options: ["Creativitas"] ,default: ["Creativitas"]}
            - { name: 'hire', label: 'Hire Developer', widget: 'select',options: ["https://www.fiverr.com/creativitas/design-your-modern-website-using-jekyll"] , default: ["https://www.fiverr.com/creativitas/design-your-modern-website-using-jekyll"]}
            - { name: 'site', label: 'Creativitas Website', widget: 'select', options: ["https://creativitas.dev"],default: ["https://creativitas.dev"]}
